version: '3.3'
services:
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        ports:
            - "27017:27017"
    seaweedfs:
        image: chrislusf/seaweedfs:latest
        container_name: crawlab_seaweedfs
        command: >
            server
            -dir=/data
            -master.dir=/data/master
            -volume.dir.idx=/data/volume
            -ip=seaweedfs
            -master.port=9333
            -volume.port=9999
            -filer
            -filer.port=8888
            -volume.minFreeSpace=1GiB
        ports:
            - "9333:9333" # SeaweedFS master
            - "9999:9999" # SeaweedFS volume, Crawlab Docker mode uses 9999
            - "8888:8888" # SeaweedFS filer, Crawlab uses this
        volumes:
            - ./seaweedfs-data:/data